package jacketjie.astimes.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.UUID;

/**
 * Entity mapped to table ATCOMMENT.
 */
public class ATComment {

    private Long id;
    /** Not-null value. */
    private String commentId;
    private String commentUserId;
    private String commentDate;
    private String commentDetail;
    private Boolean commentHasSubmit;
    /** Not-null value. */
    private String weiYuId;

    public ATComment() {
        setCommentId(UUID.randomUUID().toString());
    }

    public ATComment(Long id) {
        this.id = id;
    }

    public ATComment(Long id, String commentId, String commentUserId, String commentDate, String commentDetail, Boolean commentHasSubmit, String weiYuId) {
        this.id = id;
        this.commentId = commentId;
        this.commentUserId = commentUserId;
        this.commentDate = commentDate;
        this.commentDetail = commentDetail;
        this.commentHasSubmit = commentHasSubmit;
        this.weiYuId = weiYuId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCommentId() {
        return commentId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

    public String getCommentUserId() {
        return commentUserId;
    }

    public void setCommentUserId(String commentUserId) {
        this.commentUserId = commentUserId;
    }

    public String getCommentDate() {
        return commentDate;
    }

    public void setCommentDate(String commentDate) {
        this.commentDate = commentDate;
    }

    public String getCommentDetail() {
        return commentDetail;
    }

    public void setCommentDetail(String commentDetail) {
        this.commentDetail = commentDetail;
    }

    public Boolean getCommentHasSubmit() {
        return commentHasSubmit;
    }

    public void setCommentHasSubmit(Boolean commentHasSubmit) {
        this.commentHasSubmit = commentHasSubmit;
    }

    /** Not-null value. */
    public String getWeiYuId() {
        return weiYuId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWeiYuId(String weiYuId) {
        this.weiYuId = weiYuId;
    }

}
