package jacketjie.astimes.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.UUID;

/**
 * Entity mapped to table ATINFORMAL_ESSAY.
 */
public class ATInformalEssay {

    private Long id;
    /** Not-null value. */
    private String ATIEId;
    private String ATIEImageUrl;
    private String ATIETitle;
    private String ATIEText;
    private String ATIEReleaseDate;
    private int ATIEHasSubmit;
    private int ATIEShared;

    public ATInformalEssay() {
        setATIEId(UUID.randomUUID().toString());
    }

    public ATInformalEssay(Long id) {
        this.id = id;
    }

    public ATInformalEssay(Long id, String ATIEId, String ATIEImageUrl, String ATIETitle, String ATIEText, String ATIEReleaseDate, int ATIEHasSubmit, int ATIEShared) {
        this.id = id;
        this.ATIEId = ATIEId;
        this.ATIEImageUrl = ATIEImageUrl;
        this.ATIETitle = ATIETitle;
        this.ATIEText = ATIEText;
        this.ATIEReleaseDate = ATIEReleaseDate;
        this.ATIEHasSubmit = ATIEHasSubmit;
        this.ATIEShared = ATIEShared;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getATIEId() {
        return ATIEId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setATIEId(String ATIEId) {
        this.ATIEId = ATIEId;
    }

    public String getATIEImageUrl() {
        return ATIEImageUrl;
    }

    public void setATIEImageUrl(String ATIEImageUrl) {
        this.ATIEImageUrl = ATIEImageUrl;
    }

    public String getATIETitle() {
        return ATIETitle;
    }

    public void setATIETitle(String ATIETitle) {
        this.ATIETitle = ATIETitle;
    }

    public String getATIEText() {
        return ATIEText;
    }

    public void setATIEText(String ATIEText) {
        this.ATIEText = ATIEText;
    }

    public String getATIEReleaseDate() {
        return ATIEReleaseDate;
    }

    public void setATIEReleaseDate(String ATIEReleaseDate) {
        this.ATIEReleaseDate = ATIEReleaseDate;
    }

    public int getATIEHasSubmit() {
        return ATIEHasSubmit;
    }

    public void setATIEHasSubmit(int ATIEHasSubmit) {
        this.ATIEHasSubmit = ATIEHasSubmit;
    }

    public int getATIEShared() {
        return ATIEShared;
    }

    public void setATIEShared(int ATIEShared) {
        this.ATIEShared = ATIEShared;
    }

}
