package jacketjie.astimes.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.UUID;

/**
 * Entity mapped to table ATUSER.
 */
public class ATUser {

    private Long id;
    /** Not-null value. */
    private String userId;
    /** Not-null value. */
    private String userName;
    private String userPassword;
    private String userPhonenumber;
    /** Not-null value. */
    private String userNickName;
    private String userIcon;
    private String userSignature;
    private Integer userGender;
    private Boolean isActiveUser;
    private java.util.Date updateTime;

    public ATUser() {
        setUserId(UUID.randomUUID().toString());
    }

    public ATUser(Long id) {
        this.id = id;
    }

    public ATUser(Long id, String userId, String userName, String userPassword, String userPhonenumber, String userNickName, String userIcon, String userSignature, Integer userGender, Boolean isActiveUser, java.util.Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.userPassword = userPassword;
        this.userPhonenumber = userPhonenumber;
        this.userNickName = userNickName;
        this.userIcon = userIcon;
        this.userSignature = userSignature;
        this.userGender = userGender;
        this.isActiveUser = isActiveUser;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getUserPhonenumber() {
        return userPhonenumber;
    }

    public void setUserPhonenumber(String userPhonenumber) {
        this.userPhonenumber = userPhonenumber;
    }

    /** Not-null value. */
    public String getUserNickName() {
        return userNickName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName;
    }

    public String getUserIcon() {
        return userIcon;
    }

    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon;
    }

    public String getUserSignature() {
        return userSignature;
    }

    public void setUserSignature(String userSignature) {
        this.userSignature = userSignature;
    }

    public Integer getUserGender() {
        return userGender;
    }

    public void setUserGender(Integer userGender) {
        this.userGender = userGender;
    }

    public Boolean getIsActiveUser() {
        return isActiveUser;
    }

    public void setIsActiveUser(Boolean isActiveUser) {
        this.isActiveUser = isActiveUser;
    }

    public java.util.Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(java.util.Date updateTime) {
        this.updateTime = updateTime;
    }

}
