package jacketjie.astimes.greenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import jacketjie.astimes.greenDao.ATUser;

import jacketjie.astimes.greenDao.ATUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aTUserDaoConfig;

    private final ATUserDao aTUserDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aTUserDaoConfig = daoConfigMap.get(ATUserDao.class).clone();
        aTUserDaoConfig.initIdentityScope(type);

        aTUserDao = new ATUserDao(aTUserDaoConfig, this);

        registerDao(ATUser.class, aTUserDao);
    }
    
    public void clear() {
        aTUserDaoConfig.getIdentityScope().clear();
    }

    public ATUserDao getATUserDao() {
        return aTUserDao;
    }

}
