package jacketjie.astimes.greenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import jacketjie.astimes.greenDao.ATUser;
import jacketjie.astimes.greenDao.ATInformalEssay;

import jacketjie.astimes.greenDao.ATUserDao;
import jacketjie.astimes.greenDao.ATInformalEssayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aTUserDaoConfig;
    private final DaoConfig aTInformalEssayDaoConfig;

    private final ATUserDao aTUserDao;
    private final ATInformalEssayDao aTInformalEssayDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aTUserDaoConfig = daoConfigMap.get(ATUserDao.class).clone();
        aTUserDaoConfig.initIdentityScope(type);

        aTInformalEssayDaoConfig = daoConfigMap.get(ATInformalEssayDao.class).clone();
        aTInformalEssayDaoConfig.initIdentityScope(type);

        aTUserDao = new ATUserDao(aTUserDaoConfig, this);
        aTInformalEssayDao = new ATInformalEssayDao(aTInformalEssayDaoConfig, this);

        registerDao(ATUser.class, aTUserDao);
        registerDao(ATInformalEssay.class, aTInformalEssayDao);
    }
    
    public void clear() {
        aTUserDaoConfig.getIdentityScope().clear();
        aTInformalEssayDaoConfig.getIdentityScope().clear();
    }

    public ATUserDao getATUserDao() {
        return aTUserDao;
    }

    public ATInformalEssayDao getATInformalEssayDao() {
        return aTInformalEssayDao;
    }

}
